version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: solhint
    versions:
    - 3.3.2
    - 3.3.3
  - dependency-name: openzeppelin-solidity
    versions:
    - 3.3.0
    - 3.4.0
    - 3.4.1
